services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: estoque
    depends_on:
      mysql:
        condition: service_healthy # Responsible for init the node app only after mysql start finished.
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: estoque
    volumes:
      - mysql_data:/var/lib/mysql
      - ./produtos.sql:/docker-entrypoint-initdb.d/produtos.sql # Initiating the database with sample entries.
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
